zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8081/api
    a:
      path: /a/**
      url: http://localhost:8081/api
    x:
      path: /b/**
      url: http://localhost:8082/api

